name: Generate GitHub Stats Images

on:
  schedule:
    - cron: '0 0 * * *' # Se ejecuta automáticamente todas las noches
  workflow_dispatch: # Te permite ejecutarlo manualmente cuando quieras

jobs:
  generate-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Actualizado a v4 para evitar warnings

      - name: Download Stats Images
        run: |
          curl -o github-readme-stats.svg "https://github-readme-stats-readme-stats.vercel.app/api?username=leanioqui&show_icons=true&theme=transparent&hide_border=true&title_color=0071e3&icon_color=0071e3&text_color=ffffff"
          curl -o github-readme-stats-langs.svg "https://github-readme-stats-readme-stats.vercel.app/api/top-langs/?username=leanioqui&layout=compact&theme=transparent&hide_border=true&title_color=0071e3&text_color=ffffff"

      - name: Commit and Push Changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add github-readme-stats.svg github-readme-stats-langs.svg
          git commit -m "Update GitHub Stats images de forma estática" || exit 0
          git push
